version: '3'
services:
  vault_production:
    image: vault:1.6.0
    container_name: vault_unimed
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./private-volume:/vault/file:rw
      - ./vault:/vault/config:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json